version: '3.8'

services:
  bot:
    build: .
    environment:
      - REDIS__URL=redis://redis:6379
      - REDIS__PREFIX=records
      - TELEGRAM__TOKEN=${TELEGRAM__TOKEN}
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data: